# =========================
# Basic Server Settings
# =========================
server.port=8080

# Pretty-print JSON output
spring.jackson.serialization.indent_output=true

# Application Name
spring.application.name=insurance-rest-api

# Logging Levels
logging.level.root=INFO
logging.level.com.insurance=DEBUG




# =========================
# H2 Database Settings
# =========================

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true

spring.h2.console.path=/h2-console


# =========================
# MySQL Database Settings
# =========================
#spring.datasource.url=jdbc:mysql://localhost:3306/insurance_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=NewStrongPassword!
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / Hibernate settings
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# =========================
# HikariCP Connection Pool
# =========================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariPool

# =========================
# Swagger UI Dark Theme
# =========================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.customCssUrl=/swagger-ui-dark.css
springdoc.swagger-ui.path=/swagger



# =========================
# Disable Resource Caching (forces browser to reload CSS/JS)
# =========================
spring.resources.cache.period=0
spring.resources.chain.cache=false
spring.resources.chain.strategy.content.enabled=false

